### ISSUE TITLE
Fails with Time::Piece < 1.20

### ISSUE THREAD

**Issue by andk** [dshadow/time-moment-ext#1]
As per subject. Best illustrated with this overview:

http://analysis.cpantesters.org/reports_by_field?distv=Time-Moment-Ext-0.04;field=mod%3ATime%3A%3APiece;order=2nd

**Comment by dshadow** [comment]
Hi!

Thank you! I hope that next release will fix the issue...

Best regards
Konstantin Cherednichenko

KNTelecom Ukraine
